version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
    links:
      - mysql
    environment:
      - NODE_ENV
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ../synapse-users-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
